"""modified photo

Revision ID: 86000067ae33
Revises: df30d0063c16
Create Date: 2022-03-26 10:04:45.055476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86000067ae33'
down_revision = 'df30d0063c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photo_albumId_fkey', 'photo', type_='foreignkey')
    op.create_foreign_key(None, 'photo', 'album', ['albumId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.create_foreign_key('photo_albumId_fkey', 'photo', 'users', ['albumId'], ['id'])
    # ### end Alembic commands ###
