"""ondelete cascade implementacion2

Revision ID: a066b9fc6e5a
Revises: 9b5178fcc1f1
Create Date: 2022-03-26 11:05:06.324345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a066b9fc6e5a'
down_revision = '9b5178fcc1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('album_userId_fkey', 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('photo_albumId_fkey', 'photo', type_='foreignkey')
    op.create_foreign_key(None, 'photo', 'album', ['albumId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('todos_userId_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_userId_fkey', 'todos', 'users', ['userId'], ['id'])
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.create_foreign_key('photo_albumId_fkey', 'photo', 'album', ['albumId'], ['id'])
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key('album_userId_fkey', 'album', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
