"""modified photo

Revision ID: ad63f81fb129
Revises: 86000067ae33
Create Date: 2022-03-26 10:18:53.036301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad63f81fb129'
down_revision = '86000067ae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('url', sa.String(), nullable=True))
    op.add_column('photo', sa.Column('thumbnailUrl', sa.String(), nullable=True))
    op.drop_column('photo', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('photo', 'thumbnailUrl')
    op.drop_column('photo', 'url')
    # ### end Alembic commands ###
