"""modified post

Revision ID: d2c75b602e32
Revises: 9be266b8b5cb
Create Date: 2022-03-26 10:23:45.755404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c75b602e32'
down_revision = '9be266b8b5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint('post_albumId_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'users', ['userId'], ['id'])
    op.drop_column('post', 'albumId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('albumId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_albumId_fkey', 'post', 'users', ['albumId'], ['id'])
    op.drop_column('post', 'userId')
    # ### end Alembic commands ###
