"""create album

Revision ID: df30d0063c16
Revises: 89ad4d6cc753
Create Date: 2022-03-26 10:03:39.646055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df30d0063c16'
down_revision = '89ad4d6cc753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('albumId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['albumId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
